// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBGH83kOcAHdo9z0kkNiUHBhEHDq1MJzk',
    appId: '1:895315309337:web:933d540ba535d799e1cb88',
    messagingSenderId: '895315309337',
    projectId: 'project-aou-cars',
    authDomain: 'project-aou-cars.firebaseapp.com',
    storageBucket: 'project-aou-cars.firebasestorage.app',
    measurementId: 'G-WBTGXSTWVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU_tnOLCukuuQKR_ibzIxWVoqT4DirCas',
    appId: '1:895315309337:android:d50160212162594de1cb88',
    messagingSenderId: '895315309337',
    projectId: 'project-aou-cars',
    storageBucket: 'project-aou-cars.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKSILMPZw9JcnBUmo-h0yzor4FAooydlc',
    appId: '1:895315309337:ios:3e0b63458bd87d62e1cb88',
    messagingSenderId: '895315309337',
    projectId: 'project-aou-cars',
    storageBucket: 'project-aou-cars.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKSILMPZw9JcnBUmo-h0yzor4FAooydlc',
    appId: '1:895315309337:ios:3e0b63458bd87d62e1cb88',
    messagingSenderId: '895315309337',
    projectId: 'project-aou-cars',
    storageBucket: 'project-aou-cars.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBGH83kOcAHdo9z0kkNiUHBhEHDq1MJzk',
    appId: '1:895315309337:web:878a6f8cb3419c98e1cb88',
    messagingSenderId: '895315309337',
    projectId: 'project-aou-cars',
    authDomain: 'project-aou-cars.firebaseapp.com',
    storageBucket: 'project-aou-cars.firebasestorage.app',
    measurementId: 'G-KHWNF2PCPZ',
  );
}
